### PR TITLE
Add possibility to specify encryption context for secrets

### PR DESCRIPTION
**Pull request by riuvshyn**
Add possibility to specify encryption context for secrets.

### CODE REVIEW

**Comment by riuvshyn** [comment]
@givanov Hello! Thanks for looking at this PR :)
I see lint failed but I can't see what exactly wrong...

**Comment by alexouzounis** [comment]
Unfortunately we havent sorted opening prow for the OpenSource projects - let me copy the error for you while we figure out a more long term way to do this safely

```
golangci-lint run \
--enable-all \
-D gochecknoglobals \
-D gochecknoinits \
-D dupl \
--skip-files \
pkg/apis/credstash/v1alpha1/zz_generated.deepcopy.go,\
pkg/apis/credstash/v1alpha1/zz_generated.openapi.go \
--timeout 2m \
./...
pkg/credstash/credstash_secret_getter.go:36: Function 'GetCredstashSecretsForCredstashSecret' is too long (61 > 60) (funlen)
func (h *secretGetter) GetCredstashSecretsForCredstashSecret(
pkg/credstash/credstash_secret_getter.go:53:25: Error return value of `encryptionContext.Set` is not checked (errcheck)
			encryptionContext.Set(k + ":" + v)
			                     ^
pkg/event/event_constants.go:24: line is 130 characters (lll)
	MessageFailedFetchingCredstashSecret = "Failed fetching credstash secret. Key: %s. Version: %s. Table: %s. Context: %s. Error %s"
pkg/credstash/credstash_secret_getter.go:52:3: ranges should only be cuddled with assignments used in the iteration (wsl)
		for k, v := range v.Context {
		^
make: *** [Makefile:105: lint] Error 1
```

You can find the exact job prow runs here https://github.com/ouzi-dev/credstash-operator/blob/master/.prow.yaml#L19

**Comment by alexouzounis** [comment]
@riuvshyn almost ;p 

```
golangci-lint run \
--enable-all \
-D gochecknoglobals \
-D gochecknoinits \
-D dupl \
--skip-files \
pkg/apis/credstash/v1alpha1/zz_generated.deepcopy.go,\
pkg/apis/credstash/v1alpha1/zz_generated.openapi.go \
--timeout 2m \
./...
pkg/credstash/credstash_secret_getter.go:36: Function 'GetCredstashSecretsForCredstashSecret' is too long (64 > 60) (funlen)
func (h *secretGetter) GetCredstashSecretsForCredstashSecret(
pkg/event/event_constants.go:24: line is 130 characters (lll)
	MessageFailedFetchingCredstashSecret = "Failed fetching credstash secret. Key: %s. Version: %s. Table: %s. Context: %s. Error %s"
make: *** [Makefile:105: lint] Error 1

```

**Comment by givanov** [comment]
@riuvshyn I think we should just ignore those 2 lint issues for now. If you stick a 
> //nolint
comment on top of the 2 affected lines we should be good to go

**Comment by alexouzounis** [comment]
Thanks for your PR @riuvshyn - a new release should be happening as we speak

**Comment by alexouzounis** [comment]
or not - since we forgot to update the subject of the PR with a `release` trigger

**Comment by riuvshyn** [comment]
Thanks for cool stuff guys and for your great reactivity on reviewing it!

**Pull request merged**
